Print PASS or FAIL on same line as test name

diff --git a/xctest b/xctest
--- a/xctest
+++ b/xctest
@@ -86,11 +86,16 @@ do
 	echo Piping a $lines line file to xclip
 	for sel in primary secondary clipboard buffer
 	do
-		echo "  Using the $sel selection"
+		echo -n "  Using the $sel selection	"
 		cat $tempi | $checker ./xclip -sel $sel -i
 		sleep $delay
 		$checker ./xclip -sel $sel -o > $tempo
-		diff $tempi $tempo
+		if diff $tempi $tempo; then
+		    echo "PASS"
+		else
+		    echo "FAIL"
+		    exit 1
+		fi
 	done
 	echo
 
@@ -98,11 +103,16 @@ do
 	echo Reading a $lines line file with xclip
 	for sel in primary secondary clipboard buffer
 	do
-		echo "  Using the $sel selection"
+		echo -n "  Using the $sel selection	"
 		$checker ./xclip -sel $sel -i $tempi
 		sleep $delay
 		$checker ./xclip -sel $sel -o > $tempo
-		diff $tempi $tempo
+		if diff $tempi $tempo; then
+		    echo "PASS"
+		else
+		    echo "FAIL"
+		    exit 1
+		fi
 	done
 	echo
 	
@@ -110,10 +120,15 @@ do
 	echo Filtering a $lines line file through xclip
 	for sel in primary secondary clipboard buffer
 	do
-		echo "  Using the $sel selection"
+		echo -n "  Using the $sel selection	"
 		$checker ./xclip -sel $sel -f < $tempi > $tempo
 		sleep $delay
-		diff $tempi $tempo
+		if diff $tempi $tempo; then
+		    echo "PASS"
+		else
+		    echo "FAIL"
+		    exit 1
+		fi
 	done
 	echo
 
