Cleanup test script
* fix shellcheck warnings
* fix mix of tabs & spaces
* make compatible with more shells

Doesn't change any functionality, while making the code more robust.

diff --git a/xctest b/xctest
--- a/xctest
+++ b/xctest
@@ -1,15 +1,15 @@
 #!/bin/sh -e
 #
-#  
-# 
+#
+#
 #  xctest - shell script to test xclip
 #  Copyright (C) 2001 Kim Saunders
-# 
+#
 #  This program is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
 #  the Free Software Foundation; either version 2 of the License, or
 #  (at your option) any later version.
-# 
+#
 #  This program is distributed in the hope that it will be useful,
 #  but WITHOUT ANY WARRANTY; without even the implied warranty of
 #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
@@ -20,38 +20,37 @@
 
 cleanup() {
     # quietly remove temp files
-    rm $tempi $tempo 2> /dev/null
-    # Kill any remain xclip processes
-    killall xclip 2> /dev/null
+    rm "$tempi" "$tempo" 2>/dev/null
+    # Kill any remaining xclip processes
+    killall xclip 2>/dev/null
 }
 trap cleanup EXIT HUP INT
 
 
+s() { [ "$1" != "1" ] && printf "s"; } 	# Plural(s)
 
 delay=0.01   # seconds to wait before running xclip -o
 if ! sleep $delay  2>/dev/null; then
     delay=1
-fi    
+fi
 
 # test to make sure ./xclip exists
-if [ ! -x xclip ];
-then
+if [ ! -x xclip ]; then
     echo "Error: xclip doesn't exist in the current directory."
     exit
 fi
 
 checker=""
 
-for param in $@;
-do
+for param in "$@"; do
     case $param in
-	--valgrind) checker="valgrind --num-callers=8";;
+        --valgrind) checker="valgrind --num-callers=8";;
     esac
 done
 
 echo -n "Testing whether xclip exits correctly when the selection is lost: "
 echo hello | ./xclip -q -i 2>/dev/null &
-sleep $delay
+sleep "$delay"
 echo goodbye | ./xclip -i
 sleep $delay
 if ps $! > /dev/null; then
@@ -99,27 +98,22 @@ echo PASS
 # test xclip on different amounts of data (2^fold) to bring out any errors
 c=0			# Number of folds completed.
 lines=1			# Current file size (2 to the c power).
-echo -n 'ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-=` ' > $tempi
-echo    'abcdefghijklmnopqrstuvwzyz!@#$%^&*()_+~' >> $tempi
-for fold in 1 4 7 10 13
-do
-    # double size of file to two to the $fold power
-    while [ $c -lt $fold ]
-    do
-	cat $tempi $tempi > $tempo  &&  mv $tempo $tempi
+printf 'ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-=`[],.\t ' > "$tempi"
+printf 'abcdefghijklmnopqrstuvwzyz!@#$%^&*()_+~{}<>\n' >> "$tempi"
+for fold in 1 4 7 10 13; do
+    # double size of file by two (2 to the $fold power)
+    while [ "$c" -lt "$fold" ]; do
+	cat "$tempi" "$tempi" > "$tempo"  &&  mv "$tempo" "$tempi"
 	lines=$(( 2 * lines ))
 	c=$(( c + 1 ))
     done
 
-    echo
-    echo "Testing using $lines lines of text"
-    for sel in primary secondary clipboard buffercut
-    do
-	echo -n "$sel:	"
-
-	# test piping the file to xclip, using all selections
-	cat $tempi | $checker ./xclip -sel $sel -i
-	sleep $delay
+    # test piping the file to xclip, using all selections
+    printf "\nPiping %d line%s of text to xclip: " "$lines" $(s "$lines")
+    for sel in primary secondary clipboard buffercut; do
+        printf '%s' "  Using the $sel selection	"
+	cat "$tempi" | $checker ./xclip -sel "$sel" -i
+	sleep "$delay"
 	$checker ./xclip -sel $sel -o > $tempo
 	if ! diff $tempi $tempo; then
 	    echo
@@ -143,33 +137,34 @@ do
     
 	# test xclip filtering a file
 	$checker ./xclip -sel $sel -f < $tempi > $tempo
-	sleep $delay
-	if ! diff $tempi $tempo; then
-	    echo "FAIL"
-	    exit 1
-	else
-	    echo "Filter PASS	"
-	fi
+	sleep "$delay"
+        if diff "$tempi" "$tempo"; then
+            echo "PASS"
+        else
+            echo "FAIL"
+            exit 1
+        fi
     done
 done
 
 # test xclip on files >1MB to force INCR mode.
 echo
-echo "Binary files large enough to force INCR mode"
 for i in 1 2 16 64; do
-    dd if=/dev/zero bs=1024 count=$((i*1024)) of=$tempi >/dev/null 2>&1
-    echo -n "Trying: ($i MB)	"
+    dd if=/dev/zero bs=1024 count=$((i*1024)) of="$tempi" >/dev/null 2>&1
+    printf "Binary file large enough to force INCR mode ($i MB)\t"
     # Note: not testing "buffercut" because it cannot do INCR.
-    for sel in primary secondary clipboard
-    do
-	echo -n "$sel  	"
-	$checker ./xclip -sel $sel -i -t image/jpeg < $tempi
-	sleep $delay
-	$checker ./xclip -sel $sel -o -t image/jpeg > $tempo
-	if ! diff $tempi $tempo; then
-	    echo "FAIL: xclip could not transfer $i MB using the $sel selection"
-	    exit 1
-	fi
+    for sel in primary secondary clipboard; do
+	printf "$sel\t"
+	$checker ./xclip -sel "$sel" -i -t image/jpeg < "$tempi"
+	sleep "$delay"
+	$checker ./xclip -sel "$sel" -o -t image/jpeg > "$tempo"
+        if diff "$tempi" "$tempo"; then
+            echo "PASS"
+        else
+            echo "FAIL"
+	    echo "xclip could not transfer $i MB using the $sel selection"
+            exit 1
+        fi
     done
     echo
 done
@@ -179,5 +174,4 @@ echo "PASS"
 killall xclip
 
 # quietly remove temp files
-rm $tempi $tempo 2> /dev/null
-
+rm "$tempi" "$tempo" 2>/dev/null
