Merge hackerb9's xctest
Previous xctest was failing because, ironically, it had a bug that should have
caused xclip to fail, but xclip wasn't checking the error messages and so
reported everything was fine.

diff --git a/xctest b/xctest
--- a/xctest
+++ b/xctest
@@ -139,6 +139,30 @@ for fold in 0 4 7 10 15; do
 	    exit 1
 	fi
 	printf "$PASS"
+
+	# test xclip reading the file
+	printf "\tRead "
+	$checker ./xclip -sel $sel -i $tempi
+	sleep $delay
+	$checker ./xclip -sel $sel -o > $tempo
+	if ! diff $tempi $tempo; then
+	    echo "$FAIL"
+	    echo "Could not read a $lines-line file into the $sel selection"
+	    exit 1
+	fi
+	printf "$PASS"
+    
+	# test xclip filtering a file
+	printf "\tFilter "
+	$checker ./xclip -sel $sel -f < $tempi > $tempo
+	sleep "$delay"
+        if ! diff "$tempi" "$tempo"; then
+            echo "$FAIL"
+	    echo "Could not filter $nlines of text through the $sel selection"
+            exit 1
+        fi
+        printf "$PASS"
+
     done
 
     # test piping the file to xclip
