Allow to specify stdin as "-"
It is wide spread convention to use dash as stdin where file name
argument is expected. E.g. it is convenient to have common user
configurable command where either real file or `-` could be substituted:

    xclip -in -target %t %f

diff --git a/xctest b/xctest
--- a/xctest
+++ b/xctest
@@ -139,9 +139,30 @@ for fold in 0 4 7 10 15; do
 	    exit 1
 	fi
 	printf "$PASS"
+    done
 
-	# test xclip reading the file
-	printf "\tRead "
+    # test piping the file to xclip
+    echo Piping a $lines line file to xclip using -
+    for sel in primary secondary clipboard buffer
+    do
+	echo -n "  Using the $sel selection	"
+	cat $tempi | $checker ./xclip -sel $sel -i -
+	sleep $delay
+	$checker ./xclip -sel $sel -o > $tempo
+	if diff $tempi $tempo; then
+	    echo "PASS"
+	else
+	    echo "FAIL"
+	    exit 1
+	fi
+    done
+    echo
+
+    # test xclip reading the file
+    echo Reading a $lines line file with xclip
+    for sel in primary secondary clipboard buffer
+    do
+	echo -n "  Using the $sel selection	"
 	$checker ./xclip -sel $sel -i $tempi
 	sleep $delay
 	$checker ./xclip -sel $sel -o > $tempo
