Reindent to 4 spaces, same as .c files

diff --git a/xctest b/xctest
--- a/xctest
+++ b/xctest
@@ -19,10 +19,10 @@
 #  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
 cleanup() {
-	# quietly remove temp files
-	rm $tempi $tempo 2> /dev/null
-	# Kill any remain xclip processes
-	killall xclip 2> /dev/null
+    # quietly remove temp files
+    rm $tempi $tempo 2> /dev/null
+    # Kill any remain xclip processes
+    killall xclip 2> /dev/null
 }
 trap cleanup EXIT HUP INT
 
@@ -37,17 +37,17 @@ fi
 # test to make sure ./xclip exists
 if [ ! -x xclip ];
 then
-	echo "Error: xclip doesn't exist in the current directory."
-	exit
+    echo "Error: xclip doesn't exist in the current directory."
+    exit
 fi
 
 checker=""
 
 for param in $@;
 do
-	case $param in
-		--valgrind) checker="valgrind --num-callers=8";;
-	esac
+    case $param in
+	--valgrind) checker="valgrind --num-callers=8";;
+    esac
 done
 
 echo "Testing whether xclip exits correctly when the selection is lost"
@@ -56,11 +56,11 @@ sleep $delay
 echo goodbye | ./xclip -i
 sleep $delay
 if ps $! > /dev/null; then
-	echo "FAIL: Zombie xclip yet lives! Killing."
-	killall xclip
+    echo "FAIL: Zombie xclip yet lives! Killing."
+    killall xclip
     exit 1
 else
-	echo "PASS: xclip exited correctly after losing selection"
+    echo "PASS: xclip exited correctly after losing selection"
 fi
 
 # temp file names (in and out)
@@ -74,63 +74,63 @@ echo -n -e "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890_ "  > $tempi
 echo -n -e "abcdefghijklmnopqrstuvwzyz!@#$%^&*()\n" >> $tempi
 for fold in 1 4 7 10 13
 do
-	# double size of file by two
-	while [ $c -lt $fold ]
-	do
-		cat $tempi $tempi > $tempo  &&  mv $tempo $tempi
-		lines=$(( 2 * lines ))
-		c=$(( c + 1 ))
-	done
+    # double size of file by two
+    while [ $c -lt $fold ]
+    do
+	cat $tempi $tempi > $tempo  &&  mv $tempo $tempi
+	lines=$(( 2 * lines ))
+	c=$(( c + 1 ))
+    done
 
-	# test piping the file to xclip, using all selections
-	echo Piping a $lines line file to xclip
-	for sel in primary secondary clipboard buffer
-	do
-		echo -n "  Using the $sel selection	"
-		cat $tempi | $checker ./xclip -sel $sel -i
-		sleep $delay
-		$checker ./xclip -sel $sel -o > $tempo
-		if diff $tempi $tempo; then
-		    echo "PASS"
-		else
-		    echo "FAIL"
-		    exit 1
-		fi
-	done
-	echo
+    # test piping the file to xclip, using all selections
+    echo Piping a $lines line file to xclip
+    for sel in primary secondary clipboard buffer
+    do
+	echo -n "  Using the $sel selection	"
+	cat $tempi | $checker ./xclip -sel $sel -i
+	sleep $delay
+	$checker ./xclip -sel $sel -o > $tempo
+	if diff $tempi $tempo; then
+	    echo "PASS"
+	else
+	    echo "FAIL"
+	    exit 1
+	fi
+    done
+    echo
 
-	# test xclip reading the file
-	echo Reading a $lines line file with xclip
-	for sel in primary secondary clipboard buffer
-	do
-		echo -n "  Using the $sel selection	"
-		$checker ./xclip -sel $sel -i $tempi
-		sleep $delay
-		$checker ./xclip -sel $sel -o > $tempo
-		if diff $tempi $tempo; then
-		    echo "PASS"
-		else
-		    echo "FAIL"
-		    exit 1
-		fi
-	done
-	echo
-	
-	# test xclip filtering a file
-	echo Filtering a $lines line file through xclip
-	for sel in primary secondary clipboard buffer
-	do
-		echo -n "  Using the $sel selection	"
-		$checker ./xclip -sel $sel -f < $tempi > $tempo
-		sleep $delay
-		if diff $tempi $tempo; then
-		    echo "PASS"
-		else
-		    echo "FAIL"
-		    exit 1
-		fi
-	done
-	echo
+    # test xclip reading the file
+    echo Reading a $lines line file with xclip
+    for sel in primary secondary clipboard buffer
+    do
+	echo -n "  Using the $sel selection	"
+	$checker ./xclip -sel $sel -i $tempi
+	sleep $delay
+	$checker ./xclip -sel $sel -o > $tempo
+	if diff $tempi $tempo; then
+	    echo "PASS"
+	else
+	    echo "FAIL"
+	    exit 1
+	fi
+    done
+    echo
+    
+    # test xclip filtering a file
+    echo Filtering a $lines line file through xclip
+    for sel in primary secondary clipboard buffer
+    do
+	echo -n "  Using the $sel selection	"
+	$checker ./xclip -sel $sel -f < $tempi > $tempo
+	sleep $delay
+	if diff $tempi $tempo; then
+	    echo "PASS"
+	else
+	    echo "FAIL"
+	    exit 1
+	fi
+    done
+    echo
 
 done
 
@@ -139,16 +139,16 @@ dd if=/dev/zero bs=1024 count=4096 of=$tempi >/dev/null 2>&1
 echo Binary file large enough to force INCR mode
 for sel in primary secondary clipboard buffer
 do
-	echo -n "  Using the $sel selection	"
-	$checker ./xclip -sel $sel -i -t image/jpeg < $tempi
-	sleep $delay
-	$checker ./xclip -sel $sel -o -t image/jpeg > $tempo
-	if diff $tempi $tempo; then
-		echo "PASS"
-	else
-		echo "FAIL"
-		exit 1
-	fi
+    echo -n "  Using the $sel selection	"
+    $checker ./xclip -sel $sel -i -t image/jpeg < $tempi
+    sleep $delay
+    $checker ./xclip -sel $sel -o -t image/jpeg > $tempo
+    if diff $tempi $tempo; then
+	echo "PASS"
+    else
+	echo "FAIL"
+	exit 1
+    fi
 done
 
 
